host: "{{ inventory_hostname }}"

cert_length_days: 3650

mqtt_host: "mosquitto.home"
mqtt_enable_tls: "true" #8883
mqtt_enable_tcp: "true" #1883
mqtt_user: "mqtt"
mqtt_password: "{{ mqtt_secret_pw }}"

zigbee_mqtt_port: 8883
zigbee_serial_device_port: "/dev/ttyACM0"

git_url: https://github.com/mattbakercake

required_roles:
 - ansible-role-self-signed-cert
 - ansible-role-install-docker
 - ansible-role-container-homeassistant
 - ansible-role-container-mosquitto
 - ansible-role-container-nodered
 - ansible-role-container-zigbee2mqtt
